### ISSUE TITLE
Getting SSL cert verify failed.. using API version 2.228

### ISSUE THREAD

**Issue by jimezdoesit** [waldur/python-freeipa#10]
Using below example & getting below error. Is the IPA API v2.228 ok? 

Example from documentation:
from python_freeipa import Client
client = Client('ipaserver.domain.com', version='2.228')
client.login('admin', 'password123')
user = client.user_add('Welcome123', 'John', 'Doe', 'John Doe', preferred_language='EN')
print user

Below error:
requests.exceptions.SSLError: HTTPSConnectionPool(host='ipaserver.domain.com', port=443): Max retries exceeded with url: /ipa/session/login_password (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)'),))

Thx for your time!

**Comment by AmbientLighter** [comment]
@jimezdoesit Could you please try the same code but without SSL verification?

```
from python_freeipa import Client
client = Client('ipaserver.domain.com', version='2.228', verify_ssl=False)
client.login('admin', 'password123')
user = client.user_add('Welcome123', 'John', 'Doe', 'John Doe', preferred_language='EN')
print user

```

**Comment by jimezdoesit** [comment]
@AmbientLighter That worked! Thanks for that. Is there anyway to get the SSL to work? Can you point me in the right direction?

**Comment by AmbientLighter** [comment]
What you need is server-side authentication. The server has to prove it's identity. As your are connecting to an internal server requests doesn't have this server certificate in it's supplied bundle and therefore can't confirm the servers identity. You have to supply requests with your internal CA-bundle. To do this you have to extract it from your browser first.

See also: https://stackoverflow.com/a/14776085/6917997

When CA is downloaded, you shold pass verify_ssl the path to a CA_BUNDLE file or directory with certificates of trusted CAs:

```
client = Client('ipaserver.domain.com', version='2.228', verify_ssl='/path/to/certfile')
```

Alternatively this list of trusted CAs can also be specified through the REQUESTS_CA_BUNDLE environment variable.

See also: http://docs.python-requests.org/en/latest/user/advanced/#ssl-cert-verification
