### ISSUE TITLE
support for sudorule-add-user

### ISSUE THREAD

**Issue by shivamgupta01** [waldur/python-freeipa#18]
Hello Team,

I am trying to automate user creation in my ORG. 

I would like to request sudorule-add-user to be included in the module. Currently from my Python script we need to call "ipa sudorule-add-user --users=test.test <sudo_rule>".  This requires IPA to be installed on the server where this scrip is being executed. 

I would be great if we can have the feature in this module.

Regards,
Shivam Kumar Gupta

**Comment by AmbientLighter** [comment]
This feature has been fixed in https://github.com/opennode/python-freeipa/pull/25
