### ISSUE TITLE
Support for Python 3

### ISSUE THREAD

**Issue by HeMan** [waldur/python-freeipa#19]
Since Python 2 is EOL in January 2020, is there any plans to support Python 3?

**Comment by AmbientLighter** [comment]
We already support Python 3.
See also Travis build on Python 3: https://travis-ci.org/opennode/python-freeipa/jobs/526468923
Do you have any issues with Python-FreeIPA on Python 3?

**Comment by HeMan** [comment]
I just tried to dumb down my code to see where it fails and it seems that some of my logging code was the one to blame.
