### ISSUE TITLE
ValidationError and __str__()

### ISSUE THREAD

**Issue by relrod** [waldur/python-freeipa#24]
Right now there are several functions which call `parse_hostgroup_management_error` and `parse_group_management_error` to raise a `ValidationError` when a (host)group can't be modified for some reason.

These parsing functions set up an exception but they make the `message` a `dict` instead of a `str`. 

So the exception that gets shown is rather unhelpful: `python_freeipa.exceptions.ValidationError: <unprintable ValidationError object>`

and when the exception gets printed (or converted to `str` for displaying elsewhere), another exception gets raised: `TypeError: __str__ returned non-string (type dict)`.

I'm happy to send a PR to fix this, but I'm not sure of the best way forward, there are a few options:

* We can just have `FreeIPAError#__str__` call `str` before it returns. Then when a `ValidationError` gets thrown, the message that gets shown is the raw `dict` which is ugly but probably better than what happens right now. It also affords backwards compatibility and shouldn't break people who have worked around this issue already.
* We can have the parsing functions parse out the string(s) that contain(s) the actual error(s), which I think might have been the original intent here, but this gets gnarly when dealing with the case where multiple errors are returned at the same time:

```
# omitted: some hacks to dump out the dict
>>> client.group_add_member('cool-people', ['relrod', 'asdfasdf'])
python_freeipa.exceptions.ValidationError: {'member': {'user': [['relrod', 'This entry is already a member'], ['asdfasdf', 'no matching entry found']], 'group': [], 'service': []}}
```

* We can keep things as-is and tell users to just catch the exception and accept that `#message` is a dict and that the stack trace itself will never show a meaningful error from IPA until the user calls `#message` and processes the dict themselves.

* ... other ideas here ...

Thoughts?

**Comment by livenson** [comment]
What about making https://github.com/opennode/python-freeipa/blob/6587b076f00e192408d97ce5843de4e32d92879c/src/python_freeipa/exceptions.py#L16 a bit smarter and let it handle dicts as well?

I don't have strong opinions about the fix, apart from it being backward compatible.

**Comment by AmbientLighter** [comment]
@relrod This is a valid point. Here's a commit to fix this issue: https://github.com/opennode/python-freeipa/commit/0fc1dacb7dcd10d3df8df9e0a25d415ce7c96e46

**Comment by AmbientLighter** [comment]
It is interesting to note, however, that FreeIPA server supports partial execution of a request. For example, in this particular case it tries to add users to the group, even if there are no such users or if they are already added to the group. Therefore it does not consider this request as an invalid and does not return error message in standard format.

**Comment by AmbientLighter** [comment]
See also another commit to address this issue: https://github.com/opennode/python-freeipa/commit/e150933954705bde4f4d6640287af73859fa8349

**Comment by AmbientLighter** [comment]
As a conclusion, `message` can be either string or dict. Therefore, users are expected to parse it to get more details.

**Comment by relrod** [comment]
@AmbientLighter Fair enough! Thanks for the quick fixes! I'll very likely be sending some PRs to add group-member-manager functions. This is a new feature in IPA that lets select members ("managers") of a group have permissions to add/remove people from groups they manage -- this is something I need in a project I'm working on, but for now I'm calling `_request` and manually setting up the calls.
