### ISSUE TITLE
No authenticated session or no object 'user_add' found

### ISSUE THREAD

**Issue by jsievertde** [waldur/python-freeipa#30]
Hello,

it could be that I'm using your software wrong but when I try to use your API to communicate with the FreeIPA Server. I seem to get an authenticated Session but can't use any of the functions.

```
from python_freeipa import Client
client = Client('XXX', version='2.215')
client.login('admin', 'XXX')
user = client.user_add('test3', 'John', 'Doe', 'John Doe', preferred_language='EN')
print(user)
```
I get the following message back 
```
AttributeError: 'Client' object has no attribute 'user_add'
```
I would appreciate your guidance if i did simply misuse your software.

**Comment by AmbientLighter** [comment]
As it has been described in docs, there's a breaking changes in 1.0 release

> Previously, Python FreeIPA client covered only small fraction of FreeIPA API calls. By introducing code generator we cover all FreeIPA API calls. By default autogenerated client is used. It has different API signatures. Therefore if you want to preserve old behaviour you should just use ClientLegacy instead of Client. For example:


```
from python_freeipa import ClientLegacy
client = ClientLegacy('ipa.demo1.freeipa.org', version='2.215')
client.login('admin', 'Secret123')

```

**Comment by schlitzered** [comment]
@Uriel12: you have to use ClientMeta, instead of Client.

ClientMeta and the ClientLegacy class are subclasses of Client. The Client class only implements stuff that is common between ClientMeta and ClientLegacy.

**Comment by jsievertde** [comment]
@AmbientLighter @schlitzered 

Thank you both. After I reread the documentation I noticed the difference and now it works.
It's a nifty tool to migrate roughly 5000 thousand users to a new authentication infrastructure.
@AmbientLighter 
Thanks for all the work. I really appreciate this.
