### ISSUE TITLE
Error "Unknown option: skip_host_check" in service_add method

### ISSUE THREAD

**Issue by MikeGoltsov** [waldur/python-freeipa#41]
Hi
On new version of FreeIPA when I try to use client.service_add(a_krbcanonicalname='HTTP/'+fqdn) I recieve error:
```
  File "./ipa-certs.py", line 48, in AddCert
    client.service_add(a_krbcanonicalname='HTTP/'+fqdn)
  File "/Users/rus/Library/Python/3.7/lib/python/site-packages/python_freeipa/client_meta.py", line 19190, in service_add
    return self._request(method, _args, _params)
  File "/Users/rus/Library/Python/3.7/lib/python/site-packages/python_freeipa/client.py", line 335, in _request
    parse_error(error)
  File "/Users/rus/Library/Python/3.7/lib/python/site-packages/python_freeipa/exceptions.py", line 117, in parse_error
    raise exception_class(message, code)
python_freeipa.exceptions.UnknownOption: Unknown option: skip_host_check
```
python-freeipa ver: 1.0.5
FreeIPA, version: 4.6.5
Python 3.7.3

**Comment by schlitzered** [comment]
the api is always build against the latest freeipa release, and it seems like the latest release introduced the switch called "skip_host_check".

i checked against freeipa 4.6.6, and this version also do not have this switch in the command service_add.

you could try to create the ClientMeta on your own, against your version of freeipa, then the switch should be gone.

the process is explained here: https://python-freeipa.readthedocs.io/en/latest/

unfortunately, there is no easy way to support multiple version of the freeipa, within the same client package.

**Comment by MikeGoltsov** [comment]
I have update FreeIPA to 4.8.4 and problem is gone, thanks!
