### ISSUE TITLE
Defaults should be set to None in function otptoken_find()

### ISSUE THREAD

**Issue by james02135** [waldur/python-freeipa#43]

**Comment by james02135** [comment]
@abompard

**Comment by abompard** [comment]
Let me give a bit more context: the [otptoken_find](https://github.com/opennode/python-freeipa/blob/develop/src/python_freeipa/client_meta.py#L14922) method has defaults for its parameters that are similar to the `otptoken_add` method. While it's appropriate for the `add` function, it sets default search parameters for the `find` function that make it counter-intuitive: calling it with no args will only return tokens that have been created with the default values, while the `ipa otptoken-find` command line tool would give all the tokens.
